name: Rust

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    name: Build, test, format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --workspace --verbose

      - name: Test
        run: cargo test --workspace --verbose

      - name: Format check
        run: cargo fmt --all -- --check
